### ISSUE TITLE
was this board built?

### ISSUE THREAD

**Issue by aholtzma** [westonb/artix7-PCIe#1]
I see you sent this board off to fab. Was it built? Did you need to make any changes to make it work?

**Comment by timkpaine** [comment]
Im also interested to know if this worked, im working on a very similar board, basically a stripped down AC701 with just the pcie, Ethernet, DDR, SD, and jtag, and could use your board as a reference.

**Comment by timkpaine** [comment]
https://oshpark.com/shared_projects/hLGqMXZK

**Comment by westonb** [comment]
Board was built, before I could finish verifying everything I killed the FPGA with a JTAG ground loop. Future version I am going to add some buffers / protection on the JTAG lines. Have not had time to make more boards. 

You are probably going to need to add more PCB layers for DRAM.
